#!/bin/bash

echo Installing dependencies
go get -u github.com/golang/dep/cmd/dep
dep ensure

echo Updating gometalinter
go get -u github.com/alecthomas/gometalinter

echo Installing gometalinter dependencies
gometalinter --install